import = ["~/.alacritty-colorscheme/themes/gruvbox_dark.yaml"]

[env]
TERM = "xterm-256color"

[font]
normal = { family = "IosevkaTerm Nerd Font Mono", style = "Light" }
bold = { family = "IosevkaTerm Nerd Font Mono", style = "Bold" }
italic = { family = "IosevkaTerm Nerd Font Mono", style = "Italic" }
size = 16

[colors]
transparent_background_colors = true

[window]
opacity = 0.95
