import = ["~/.config/alacritty/themes/themes/gruvbox_dark.toml"]

[env]
TERM = "xterm-256color"

[font]
normal = { family = "IosevkaTerm Nerd Font Mono", style = "Light" }
bold = { family = "IosevkaTerm Nerd Font Mono", style = "Bold" }
italic = { family = "IosevkaTerm Nerd Font Mono", style = "Italic" }
size = 14.5

[colors]
transparent_background_colors = true

[window]
opacity = 0.95
